name: "Sign"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 打卡时间

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install depend
      run: |
        pip install --upgrade pip
        pip install pytz
        pip install pycryptodome

    - name: Start sign
      env:
        USERS: ${{ secrets.USERS }}
      run: |
        python test.py
      
    - name: Generate logs.txt
      run: echo "This is a test log" > logs.txt

    - name: Debug - Check logs.txt
      run: ls -lah logs.txt

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs.txt
              
    - name: Download logs
      uses: actions/download-artifact@v2
      with:
        name: logs

    - name: Save logs to repo
      run: |
        mkdir -p artifacts
        mv logs.txt artifacts/logs.txt

    - name: Send logs to QQ Email
      run: |
        python send_email.py
