name: "Sign"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 打卡时间

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytz
        pip install pycryptodome

    - name: Start sign
      env:
        USERS: ${{ secrets.USERS }}
      run: |
        python test.py

    - name: Capture build logs
      id: capture-logs
      run: |
        mkdir -p logs
        # Redirect both standard output and error output to the log file
        python test.py > logs/build.log 2>&1

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs

    - name: Send logs to QQ Email
      run: |
        # Use your email script here, and attach the log file
        python send_email.py logs/build.log
