name: "Sign"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 打卡时间

env:
  EMAIL_SUBJECT: "GitHub Actions Sign Workflow Logs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install depend
      run: |
        pip install requests
        pip install json5
        pip install pytz
        pip install pycryptodome
        pip install python-mimeparse
        pip install postfix

    - name: Start sign
      env:
        USERS: ${{ secrets.USERS }}
      run: |
        python test.py

    - name: Send logs via email
      if: always()
      env:
        EMAIL_FROM: "GitHub Actions <github-actions@example.com>"
      run: |
        echo "Workflow logs:" >> logs.txt
        cat /home/runner/work/_temp/*.log >> logs.txt
        echo "" >> logs.txt
        echo "Artifacts link:" >> logs.txt
        echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" >> logs.txt
        echo "" >> logs.txt
        echo "Check the attached file for more details." >> logs.txt

        python -m smtplib -c DebuggingServer localhost:1025 &
        sleep 2
        python -m smtpd_client -s smtp://localhost:1025/
        python send_email.py ${{ env.EMAIL_HOST }} ${{ env.EMAIL_PORT }} ${{ env.EMAIL_USE_TLS }} ${{ env.EMAIL_USERNAME }} ${{ env.EMAIL_PASSWORD }} ${{ env.EMAIL_TO }} ${{ env.EMAIL_SUBJECT }}
        kill %1