name: Send Logs via Email

on:
  push:
    branches:
      - main

jobs:
  send_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your command and capture logs
        run: |
          your_command > logs.txt

      - name: Send email with logs
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: "smtp.qq.com"
          server_port: 465
          username: "测试任务"
          password: "qcxblsaegurtdghb"
          subject: 'GitHub Actions执行日志'
          to: 2846150854@qq.com
          from: 2846150854@qq.com
          body: '执行日志见附件。'
          attachments: 'logs.txt'
