name: Sign

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 打卡时间

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install depend
      run: |
        pip install requests
        pip install json5
        pip install pytz
        pip install pycryptodome

    - name: Start sign
      env:
        USERS: ${{ secrets.USERS }}
      run: |
        python test.py

    - name: Archive Logs
      run: |
        tar cvf logs.tar.gz *.log

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs.tar.gz

  download_logs_and_send_email:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Logs
      id: download_logs
      uses: actions/download-artifact@v2
      with:
        name: logs
        path: logs/

    - name: Extract Logs
      run: |
        tar xvf logs.tar.gz

    - name: Send Email
      env:
        SENDGRID_API_KEY: ${{ .env.EMAIL_PASSWORD }}
        FROM_EMAIL: ${{ .env.EMAIL_TO }}
        TO_EMAIL: ${{ .env.EMAIL_TO }}
      run: |
        echo "Logs for the current run:" | mailx -s "GitHub Actions Logs" -a "$RUN_LOGS" ${TO_EMAIL}